version: '3'
services:
  users:
    build: .
    ports:
     - "8080:80"
    container_name: users
    image: users
    environment:
     - TEAM_ID=CC_208_222_223_236
    networks:
     - acts_cc-net

networks:
  acts_cc-net:
     external: true

