version: '3'
services:
  acts:
    build: .
    ports:
     - "80:80"
    networks:
     - mongo-acts
    container_name: acts
    image: acts
    environment:
     - TEAM_ID=CC_208_222_223_236

  mongo:
    image: "mongo"
    container_name: mongo_acts
    networks:
     - mongo-acts

networks:
  mongo-acts:
    driver: bridge
